sudo: false
language: php
php:
  - 5.4

before_script:
  - pear channel-update pear.php.net
  - pear install pear/PHP_CodeSniffer
  - pear channel-discover pear.phing.info
  - pear clear-cache
  - pear install phing/phing

script:
  - phpcs --standard=PEAR --ignore=*/config/*,*/tests/* --extensions=php $PWD/module
  - phing php-cs-fixer-dryrun